import { Injectable, Logger } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { JwtService } from '@nestjs/jwt';
import { AccountRole } from '../../common/enums';
import { AppException } from '../../common/exceptions/app.exception';
import { Account } from '../accounts/entities/account.entity';

/** Claims of the admin/client access token. */
export interface AccountTokenPayload {
  /** Account id (UUIDv7, textual form). */
  sub: string;
  email: string;
  role: AccountRole;
  full_name: string;
  iat?: number;
  exp?: number;
}

/** Claims of the client <-> translator signature token. */
export interface SignatureTokenPayload {
  account_id: string;
  reference_id: string;
  iat?: number;
  exp?: number;
}

/**
 * Issues and verifies the two flavours of JWT used by the application:
 *
 * 1. **Access token** – signed with `JWT_SECRET`, identifies an admin/client
 *    account and is sent as `Authorization: Bearer ...` or through the
 *    `access_token` cookie.
 * 2. **Signature token** – signed with the `account_keys.secret_key` of the
 *    caller, proves that the `reference_id` of the request was generated by the
 *    owner of that key.
 */
@Injectable()
export class TokensService {
  private readonly logger = new Logger(TokensService.name);

  constructor(
    private readonly jwtService: JwtService,
    private readonly configService: ConfigService,
  ) {}

  get accessTokenTtl(): number {
    return this.configService.getOrThrow<number>('security.jwtExpiresIn');
  }

  get signatureTokenTtl(): number {
    return this.configService.getOrThrow<number>('security.signatureTokenTtl');
  }

  signAccountToken(
    account: Pick<Account, 'id' | 'email' | 'role' | 'fullName'>,
  ): Promise<string> {
    const payload: AccountTokenPayload = {
      sub: account.id,
      email: account.email,
      role: account.role,
      full_name: account.fullName,
    };

    return this.jwtService.signAsync(payload, {
      secret: this.configService.getOrThrow<string>('security.jwtSecret'),
      expiresIn: this.accessTokenTtl,
    });
  }

  async verifyAccountToken(token: string): Promise<AccountTokenPayload> {
    try {
      return await this.jwtService.verifyAsync<AccountTokenPayload>(token, {
        secret: this.configService.getOrThrow<string>('security.jwtSecret'),
      });
    } catch (error) {
      this.logger.debug(
        `Access token verification failed: ${(error as Error).message}`,
      );

      throw AppException.unauthorized('Access token is invalid or expired');
    }
  }

  signSignatureToken(
    secretKey: string,
    payload: Omit<SignatureTokenPayload, 'iat' | 'exp'>,
  ): Promise<string> {
    return this.jwtService.signAsync(payload, {
      secret: secretKey,
      expiresIn: this.signatureTokenTtl,
    });
  }

  async verifySignatureToken(
    secretKey: string,
    token: string,
  ): Promise<SignatureTokenPayload> {
    try {
      return await this.jwtService.verifyAsync<SignatureTokenPayload>(token, {
        secret: secretKey,
      });
    } catch (error) {
      this.logger.debug(
        `Signature token verification failed: ${(error as Error).message}`,
      );

      throw AppException.unauthorized('Signature token is invalid or expired');
    }
  }
}
